export const GITHUB_USERNAME = 'GITHUB_USERNAME';
export const GITHUB_LOADING = 'GITHUB_LOADING';
export const GITHUB_LOADING_ERROR = 'GITHUB_LOADING_ERROR';
export const GITHUB_LOADED = 'GITHUB_LOADED';
export const ADD_GITHUB_USER = 'ADD_GITHUB_USER';

export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR';
